# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vb0QXQJo3AhfqqrUUuHk1AFnQFccBEbf
"""

# MIS 328 - Applications Development 1
# Application Development Project
# Group 2

# Declare a list to hold week days
weekDays = ["1. Monday", "2. Tuesday", "3. Wednesday", "4. Thursday", "5. Friday", "6. Saturday", "7. Sunday"]

# Define a function to display the weekdays
def displayWeekDays():
  for weekDay in weekDays:
    print(weekDay)

# Print a message to greet the customer
print("Welcome to Adventure Park!\n")
    
# Asks the customer to input their name
customerName = str(input("Please Enter Your Name:"))

# Defines a function to display menu of available days
def customerDay():
  print("\n")
  print("==================== Pricing Options ====================")
  print("Our available days are:")
  displayWeekDays()
  print("Student's recieve a $20 discount per ticket purchased!")
  print("=========================================================")
  print("\n")

# Asks the customer if they would like to order tickets
print("\n")
orderTickets = str(input("Hello " + customerName + ", would you like to order tickets? Y/N"))

# If the customer selects "N", exit the application
if orderTickets == 'N':
  print("\n")
  print("Exiting Program...")
  exit()
  
# If the customer selects "Y"
elif orderTickets == 'Y': 

  # Calls the customerDay function to display menu of available days
  customerDay()
  #Asks the customer what day they would like to visit the park
  print("==================== Date of Visit ======================\n")
  dayOfVisit = int(input("Please enter 1-7 for your selection:"))
  print("=========================================================\n")
  # Asks the customer how many tickets they would like to order
  print("\n")
  print("================ Quantity of tickets ====================\n")
  amountOfTickets = int(input("How many tickets would you like to order?"))
  print("=========================================================\n")
  # Asks the customer if they have a student discount
  print("\n")
  print("================== Student Discount =====================\n")
  studentDiscount = str(input("Do you have a student discount? Y/N"))
  print("=========================================================\n")
# If the customer selects anything besides 'Y' or 'N', provide an error message
else:
  print("Please select a number 1-7 to select the date you would like to choose")




# If the customer selects 1 for Monday
if dayOfVisit == 1:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Monday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Monday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*65) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*65)
    print("Your total is: $" + str(total) + "\n")
    
    
    
    
# If the customer selects 2 for Tuesday
if dayOfVisit == 2:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Tuesday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Tuesday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*65) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*65)
    print("Your total is: $" + str(total) + "\n")
  
  
# If the customer selects 3 for Wednesday
if dayOfVisit == 3:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Wednesday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Wednesday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*65) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*65)
    print("Your total is: $" + str(total) + "\n")
    
    
# If the customer selects 4 for Thursday
if dayOfVisit == 4:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Thursday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Thursday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*65) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*65)
    print("Your total is: $" + str(total) + "\n")
    

# If the customer selects 5 for Friday
if dayOfVisit == 5:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Friday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Friday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*75) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*75)
    print("Your total is: $" + str(total) + "\n")
    
    
# If the customer selects 6 for Saturday
if dayOfVisit == 6:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Saturday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Saturday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*75) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*75)
    print("Your total is: $" + str(total) + "\n")
    
    
    
# If the customer selects 7 for Sunday
if dayOfVisit == 7:
  print("\n")
  print("====================== Order Total ======================\n")
  # Displays how many Sunday tickets the customer is ordering
  print("You are ordering "+ str(amountOfTickets) + " tickets for Sunday\n")
  # If the customer has a discount, calculate and display the totals
  if studentDiscount == 'Y':
    discount = (amountOfTickets*20)
    print("You are receiving a total discount of: $" + str(discount) + "\n")
    total = (amountOfTickets*75) - (amountOfTickets*20)
    print("Your total with your student discount is: $" + str(total) + "\n")
  # If the customer does not have a discount, calculate and display the total
  elif studentDiscount == 'N':
    total = (amountOfTickets*75)
    print("Your total is: $" + str(total) + "\n")

print("=========================================================\n")
# generate random integer values
from random import randint

value = randint(10000, 1000000)
print("Your conformation number is: " + str(value))

print("=========================================================\n")
print("Thank you, " + customerName + "! We cannot wait to see you at Adventure Park!\n")

